version: "3.8"
services:
  sumo:
    build:
      context: ./sumo
      dockerfile: Dockerfile
    volumes:
      - ./sumo:/sumo:rw
    depends_on:
      ai:
        condition: service_healthy
    command: ["sh", "/sumo/run_sumo.sh"]
  
  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    volumes:
      - ./ai:/ai
      - ./sumo:/sumo
    network_mode: "host"  # Usa la red del host directamente
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      retries: 5
      start_period: 5s